server:
  port: 8088
spring:
  application:
    name: MyGradle  
  redis:   
    host: 10.164.194.142     
    port: 6379    
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/orcl     
    testWhileIdle: true     
    validationQuery: SELECT 1 from dual     
    username: demo     
    password: demo     
    driverClassName: oracle.jdbc.OracleDriver   
  jpa:     
    database: ORACLE     
    show-sql: true     
    hibernate:       
      show-sql: true       
      ddl-auto: none       
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy     
    properties:       
      hibernate.dialect: org.hibernate.dialect.Oracle10gDialect       
      org.hibernate.envers.audit_table_suffix: _H       
  data:
    rest.base-path: /api       # 访问地址/api/browser/index.html
  mail:
    host: smtp.ym.163.com
    username: liupeizhen@bestvike.com
    password: 123456
    javaMailProperties:
      mail:
        smtp:
          auth: true
          timeout: 25000
common:
  address:
    extUrl: http://10.164.194.115:8081    # http://CRM 
eureka:
  client:
    register-with-eureka: true 
    fetch-registry: true 
    registryFetchIntervalSeconds: 5
    eurekaServiceUrlPollIntervalSeconds: 120
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #http://10.164.197.209:1180/eureka/ ,http://localhost:8761/eureka/
  instance:
    appname: ${spring.application.name}
    hostname: localhost
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    securePortEnabled: false     
       
       
       
       
       
       
       
         