/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '16-8-20 下午3:14' with Gradle 2.10
 *
 * @author Administrator, @date 16-8-20 下午3:14
 */
public class Library {
    public boolean someLibraryMethod() {
        System.out.println("这也是别人改的");
        System.out.println("我又加上自己的");
        return true;
    }
}
